name: shaders_playground
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.0.3
  photo_view: ^0.14.0
  rive: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0



flutter:
  uses-material-design: true
  shaders:
    - shaders/motion_blur.glsl
    - shaders/brightness.glsl
    - shaders/super_shader.glsl
    - shaders/everything.glsl
    - shaders/barrel_blur.glsl
    - shaders/boilerplate.glsl

  assets:
    - assets/